# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dkUdijSNQG7N0Xgs78sRgBBVte6j9_M
"""

x = int(input("cantidad de numeros"))
for i in range(x):
  y = int(input("ingrese el numero" + str(1)))
  def pri(y):
    for n in range(2, y):
      if n < 2:
        #print(y, "no es primo")
        #print(n, "es divisor")
        return False
      
        return True 
  if pri == True:
    print("Es primo")
  else:
    print("No es primo")

x = int(input("cantidad de numeros"))
for i in range(x):
  y = int(input("ingrese el numero" + str(1)))
  for n in range(2, y):
    if n < "2":
      print("Es primo")
    else:
      print("No es primo")

x = int(input("cantidad de numeros"))
for i in range(x):
  def isPrime(num):
    if num < 1:
        return False
    elif num == 2:
        return True
    else:
        for i in range(2, num):
            if num % i == 0:
                return False
        return True            

def app():
    num = int(input('Write a number: '))
    result = isPrime(num)
x = int(input("inserte numero "))
 for i in range(x):
   def es_primo

numero= int(input("¿Qué número quieres saber si es primo?"))
valor= range(2,numero)
contador = 0
for n in valor:
  if numero % n == 0:
    contador +=1
    print("divisor:", n)
 
if contador > 0 :
  print("El número no es primo" )
else:
  print("El nÚmero es primo")