# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2zr7H7PRnOKHWYwOki7kWOpWXrM2ows
"""

with open("test.txt","w") as fwriter:
  fwriter.write("hola mundo")

with open ("test.txt","r") as freader:
  lineas = freader.readlines()
  for x in range(len(lineas)):
    print(x," - ", lineas[x])